---
config:
  theme: base
  themeVariables:
    primaryColor: '#FFF5E4'
    edgeLabelBackground: '#FFF'
    fontFamily: verdana
---
flowchart TD
 subgraph BR1["<b>RAJALINGAM BRANCH</b>"]
    direction TB
        GP1("Yesireddy Rajalingam & Kamalamma")
        C1A("Medishetty Swarojini & Raghollu")
        C1B("Bedadha Swathanthra & Chennaiah")
        G1A("Rajesh & Raja")
        Sai("Sai")
        Swathi("Swathi")
        Sahithi("Sahithi")
        G1B("Deepa & Sathish")
        Ashwith("Ashwith")
        Vihan("Vihan")
        G1C("Yesireddy Neeraja")
        G1D("Anil & Prashanthi")
        Pragnya("Pragnya")
        Akshaya("Akshaya Sri")
        G1E("Rani & Rajendhar")
        Ashritha("Ashritha")
        G1F("Asha & Damodar")
        SaiBharath("Sai Bharath")
        G1K("Bhavya & Shiva")
        Advitha("Advitha")
        G1G("Uma & Prasad")
        G1H("Prathibha & Gowtham")
        Jasvik("Jasvik")
        Hayan("Hayan")
        Reetesh("Sai Reetesh")
  end
 subgraph BR2["<b>ESHWARAIAH BRANCH</b>"]
    direction TB
        GP2("Yesireddy Eshwaraiah & Savithriamma")
        C2A("Raja & Mohan")
        C2B("Aruna & Ajay")
        C2C("Jyothi & Ravinder")
        C2D("Rajyam & Raghav Rao")
        G2A("Rajani")
        Kiran("Kiran")
        G2B("Naveen & Ramya")
        G2C("Manasa & Sathish")
        Anshu("Anshu")
        Subbu("Subbu")
        G2D("Swathi & Sunil")
        Adithi("Adithi")
        Siddhan("Siddhan")
        G2E("Pradeep & Sravani")
        Medha("Sri Medha")
        Moksha("Sri Moksha")
        G2F("Vardhini & Pranav")
        Samanvi("Aarya Samanvi")
        Vishnu("Vishnu")
  end
 subgraph BR3["<b>JANARDHAN BRANCH</b>"]
    direction TB
        GP3("Yesireddy Janardhan & Yeshodhamma")
        C3A("Laxmi & Veeresh Babu")
        C3B("Laxminarayana & Neeraja")
        C3C("Ramesh & Rajani")
        C3D("Sumathi & Chandrashekhar")
        G3A("Varun & Sunitha")
        Kruthi("Kruthi Naira")
        Vihan2("Vihan Nandhan")
        G3B("Divya & Arun")
        Manswini("Manswini")
        Varshini("Varshini")
        G3C("Rahul & Manivitha")
        G3D("Revanth & Nandhini")
        G3E("Sneha & Gowtham")
        Shlokha("Shlokha")
        G3F("Aishwarya & Chandrashekhar")
        Aarav("Aarav")
        Aaryan("Aaryan")
        Rushali("Rushali")
        Ronith("Ronith")
  end
    ROOT("<center><b>Yesireddy Laxminarayana &amp; Yellamma</b></center>") --> GP1 & GP2 & GP3
    GP1 --> C1A & C1B
    C1A --> G1A & G1B
    G1A --> Sai & Swathi & Sahithi
    G1B --> Ashwith & Vihan
    C1B --> G1C & G1D & G1E & G1F & G1G
    G1D --> Pragnya & Akshaya
    G1E --> Ashritha
    G1F --> SaiBharath & G1K
    G1K --> Advitha
    G1G --> G1H & Reetesh
    G1H --> Jasvik & Hayan
    GP2 --> C2A & C2B & C2C & C2D
    C2A --> G2A & Kiran & G2B
    C2B --> G2C
    G2C --> Anshu & Subbu
    C2C --> G2D & G2E
    G2D --> Adithi & Siddhan
    G2E --> Medha & Moksha
    C2D --> G2F & Vishnu
    G2F --> Samanvi
    GP3 --> C3A & C3B & C3C & C3D
    C3A --> G3A & G3B & G3C
    G3A --> Kruthi & Vihan2
    G3B --> Manswini & Varshini
    C3B --> G3D & G3E & G3F
    G3E --> Shlokha
    G3F --> Aarav & Aaryan
    C3C --> Rushali & Ronith
     GP1:::branch1
     C1A:::branch1
     C1B:::branch1
     G1A:::branch1
     Sai:::branch1
     Swathi:::branch1
     Sahithi:::branch1
     G1B:::branch1
     Ashwith:::branch1
     Vihan:::branch1
     G1C:::branch1.cross
     G1D:::branch1
     Pragnya:::branch1
     Akshaya:::branch1
     G1E:::branch1
     Ashritha:::branch1
     G1F:::branch1
     SaiBharath:::branch1
     G1K:::branch1
     Advitha:::branch1
     G1G:::branch1
     G1H:::branch1
     Jasvik:::branch1
     Hayan:::branch1
     Reetesh:::branch1
     GP2:::branch2
     C2A:::branch2
     C2B:::branch2
     C2C:::branch2
     C2D:::branch2
     G2A:::branch2.cross
     Kiran:::branch2
     G2B:::branch2
     G2C:::branch2
     Anshu:::branch2
     Subbu:::branch2
     G2D:::branch2
     Adithi:::branch2
     Siddhan:::branch2
     G2E:::branch2
     Medha:::branch2
     Moksha:::branch2
     G2F:::branch2
     Samanvi:::branch2
     Vishnu:::branch2
     GP3:::branch3
     C3A:::branch3
     C3B:::branch3.cross
     C3C:::branch3.cross
     C3D:::branch3
     G3A:::branch3
     Kruthi:::branch3
     Vihan2:::branch3
     G3B:::branch3
     Manswini:::branch3
     Varshini:::branch3
     G3C:::branch3
     G3D:::branch3
     G3E:::branch3
     Shlokha:::branch3
     G3F:::branch3
     Aarav:::branch3
     Aaryan:::branch3
     Rushali:::branch3
     Ronith:::branch3
     ROOT:::root
    classDef root fill:#FFD700,stroke:#DAA520,stroke-width:3px
    classDef branch1 fill:#B0E0E6,stroke:#1E90FF,stroke-width:2px
    classDef branch2 fill:#98FB98,stroke:#2E8B57,stroke-width:2px
    classDef branch3 fill:#FFB6C1,stroke:#FF0000,stroke-width:2px
    classDef cross fill:none,stroke:#0000FF,stroke-width:3px,stroke-dasharray:3 3
    style BR1 fill:#B0E0E620,stroke:#1E90FF,stroke-width:3px
    style BR2 fill:#98FB9820,stroke:#2E8B57,stroke-width:3px
    style BR3 fill:#FFB6C120,stroke:#FF0000,stroke-width:3px
